// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/DPerson.proto

package cywl.test.proto;

public final class DPerson {
    private DPerson() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface GoodsProtoOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string name = 1;
        boolean hasName();

        String getName();

        // optional string desc = 2;
        boolean hasDesc();

        String getDesc();
    }

    public static final class GoodsProto extends
            com.google.protobuf.GeneratedMessage
            implements GoodsProtoOrBuilder {
        // Use GoodsProto.newBuilder() to construct.
        private GoodsProto(Builder builder) {
            super(builder);
        }

        private GoodsProto(boolean noInit) {
        }

        private static final GoodsProto defaultInstance;

        public static GoodsProto getDefaultInstance() {
            return defaultInstance;
        }

        public GoodsProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DPerson.internal_static_sd_fol_GoodsProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DPerson.internal_static_sd_fol_GoodsProto_fieldAccessorTable;
        }

        private int bitField0_;
        // optional string name = 1;
        public static final int NAME_FIELD_NUMBER = 1;
        private Object name_;

        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string desc = 2;
        public static final int DESC_FIELD_NUMBER = 2;
        private Object desc_;

        public boolean hasDesc() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getDesc() {
            Object ref = desc_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    desc_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getDescBytes() {
            Object ref = desc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            name_ = "";
            desc_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDescBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDescBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static GoodsProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static GoodsProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static GoodsProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static GoodsProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static GoodsProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static GoodsProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static GoodsProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static GoodsProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static GoodsProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static GoodsProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(GoodsProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements GoodsProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DPerson.internal_static_sd_fol_GoodsProto_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DPerson.internal_static_sd_fol_GoodsProto_fieldAccessorTable;
            }

            // Construct using cywl.test.proto.DPerson.GoodsProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                desc_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return GoodsProto.getDescriptor();
            }

            public GoodsProto getDefaultInstanceForType() {
                return GoodsProto.getDefaultInstance();
            }

            public GoodsProto build() {
                GoodsProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private GoodsProto buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                GoodsProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public GoodsProto buildPartial() {
                GoodsProto result = new GoodsProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.desc_ = desc_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof GoodsProto) {
                    return mergeFrom((GoodsProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(GoodsProto other) {
                if (other == GoodsProto.getDefaultInstance()) return this;
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (other.hasDesc()) {
                    setDesc(other.getDesc());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            desc_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional string name = 1;
            private Object name_ = "";

            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }

            // optional string desc = 2;
            private Object desc_ = "";

            public boolean hasDesc() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getDesc() {
                Object ref = desc_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    desc_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setDesc(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                desc_ = value;
                onChanged();
                return this;
            }

            public Builder clearDesc() {
                bitField0_ = (bitField0_ & ~0x00000002);
                desc_ = getDefaultInstance().getDesc();
                onChanged();
                return this;
            }

            void setDesc(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                desc_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:sd.fol.GoodsProto)
        }

        static {
            defaultInstance = new GoodsProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:sd.fol.GoodsProto)
    }

    public interface PersonProtoOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string name = 1;
        boolean hasName();

        String getName();

        // optional sint32 age = 2;
        boolean hasAge();

        int getAge();

        // repeated sint32 friendID = 3 [packed = true];
        java.util.List<Integer> getFriendIDList();

        int getFriendIDCount();

        int getFriendID(int index);

        // optional .sd.fol.GoodsProto equip = 4;
        boolean hasEquip();

        GoodsProto getEquip();

        GoodsProtoOrBuilder getEquipOrBuilder();

        // repeated .sd.fol.GoodsProto goodsList = 5;
        java.util.List<GoodsProto>
        getGoodsListList();

        GoodsProto getGoodsList(int index);

        int getGoodsListCount();

        java.util.List<? extends GoodsProtoOrBuilder>
        getGoodsListOrBuilderList();

        GoodsProtoOrBuilder getGoodsListOrBuilder(
                int index);

        // optional float floatTest = 6;
        boolean hasFloatTest();

        float getFloatTest();

        // optional double doubleTest = 7;
        boolean hasDoubleTest();

        double getDoubleTest();

        // optional bool trueTest = 8;
        boolean hasTrueTest();

        boolean getTrueTest();

        // optional bool falseTest = 9;
        boolean hasFalseTest();

        boolean getFalseTest();

        // repeated string noteList = 10;
        java.util.List<String> getNoteListList();

        int getNoteListCount();

        String getNoteList(int index);

        // optional bytes paramBytes = 11;
        boolean hasParamBytes();

        com.google.protobuf.ByteString getParamBytes();
    }

    public static final class PersonProto extends
            com.google.protobuf.GeneratedMessage
            implements PersonProtoOrBuilder {
        // Use PersonProto.newBuilder() to construct.
        private PersonProto(Builder builder) {
            super(builder);
        }

        private PersonProto(boolean noInit) {
        }

        private static final PersonProto defaultInstance;

        public static PersonProto getDefaultInstance() {
            return defaultInstance;
        }

        public PersonProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DPerson.internal_static_sd_fol_PersonProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DPerson.internal_static_sd_fol_PersonProto_fieldAccessorTable;
        }

        private int bitField0_;
        // optional string name = 1;
        public static final int NAME_FIELD_NUMBER = 1;
        private Object name_;

        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional sint32 age = 2;
        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        public boolean hasAge() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getAge() {
            return age_;
        }

        // repeated sint32 friendID = 3 [packed = true];
        public static final int FRIENDID_FIELD_NUMBER = 3;
        private java.util.List<Integer> friendID_;

        public java.util.List<Integer>
        getFriendIDList() {
            return friendID_;
        }

        public int getFriendIDCount() {
            return friendID_.size();
        }

        public int getFriendID(int index) {
            return friendID_.get(index);
        }

        private int friendIDMemoizedSerializedSize = -1;

        // optional .sd.fol.GoodsProto equip = 4;
        public static final int EQUIP_FIELD_NUMBER = 4;
        private GoodsProto equip_;

        public boolean hasEquip() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public GoodsProto getEquip() {
            return equip_;
        }

        public GoodsProtoOrBuilder getEquipOrBuilder() {
            return equip_;
        }

        // repeated .sd.fol.GoodsProto goodsList = 5;
        public static final int GOODSLIST_FIELD_NUMBER = 5;
        private java.util.List<GoodsProto> goodsList_;

        public java.util.List<GoodsProto> getGoodsListList() {
            return goodsList_;
        }

        public java.util.List<? extends GoodsProtoOrBuilder>
        getGoodsListOrBuilderList() {
            return goodsList_;
        }

        public int getGoodsListCount() {
            return goodsList_.size();
        }

        public GoodsProto getGoodsList(int index) {
            return goodsList_.get(index);
        }

        public GoodsProtoOrBuilder getGoodsListOrBuilder(
                int index) {
            return goodsList_.get(index);
        }

        // optional float floatTest = 6;
        public static final int FLOATTEST_FIELD_NUMBER = 6;
        private float floatTest_;

        public boolean hasFloatTest() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public float getFloatTest() {
            return floatTest_;
        }

        // optional double doubleTest = 7;
        public static final int DOUBLETEST_FIELD_NUMBER = 7;
        private double doubleTest_;

        public boolean hasDoubleTest() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public double getDoubleTest() {
            return doubleTest_;
        }

        // optional bool trueTest = 8;
        public static final int TRUETEST_FIELD_NUMBER = 8;
        private boolean trueTest_;

        public boolean hasTrueTest() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public boolean getTrueTest() {
            return trueTest_;
        }

        // optional bool falseTest = 9;
        public static final int FALSETEST_FIELD_NUMBER = 9;
        private boolean falseTest_;

        public boolean hasFalseTest() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        public boolean getFalseTest() {
            return falseTest_;
        }

        // repeated string noteList = 10;
        public static final int NOTELIST_FIELD_NUMBER = 10;
        private com.google.protobuf.LazyStringList noteList_;

        public java.util.List<String>
        getNoteListList() {
            return noteList_;
        }

        public int getNoteListCount() {
            return noteList_.size();
        }

        public String getNoteList(int index) {
            return noteList_.get(index);
        }

        // optional bytes paramBytes = 11;
        public static final int PARAMBYTES_FIELD_NUMBER = 11;
        private com.google.protobuf.ByteString paramBytes_;

        public boolean hasParamBytes() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        public com.google.protobuf.ByteString getParamBytes() {
            return paramBytes_;
        }

        private void initFields() {
            name_ = "";
            age_ = 0;
            friendID_ = java.util.Collections.emptyList();
            ;
            equip_ = GoodsProto.getDefaultInstance();
            goodsList_ = java.util.Collections.emptyList();
            floatTest_ = 0F;
            doubleTest_ = 0D;
            trueTest_ = false;
            falseTest_ = false;
            noteList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            paramBytes_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeSInt32(2, age_);
            }
            if (getFriendIDList().size() > 0) {
                output.writeRawVarint32(26);
                output.writeRawVarint32(friendIDMemoizedSerializedSize);
            }
            for (int i = 0; i < friendID_.size(); i++) {
                output.writeSInt32NoTag(friendID_.get(i));
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeMessage(4, equip_);
            }
            for (int i = 0; i < goodsList_.size(); i++) {
                output.writeMessage(5, goodsList_.get(i));
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeFloat(6, floatTest_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeDouble(7, doubleTest_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBool(8, trueTest_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBool(9, falseTest_);
            }
            for (int i = 0; i < noteList_.size(); i++) {
                output.writeBytes(10, noteList_.getByteString(i));
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(11, paramBytes_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(2, age_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < friendID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeSInt32SizeNoTag(friendID_.get(i));
                }
                size += dataSize;
                if (!getFriendIDList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                friendIDMemoizedSerializedSize = dataSize;
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, equip_);
            }
            for (int i = 0; i < goodsList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, goodsList_.get(i));
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(6, floatTest_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(7, doubleTest_);
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(8, trueTest_);
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(9, falseTest_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < noteList_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(noteList_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getNoteListList().size();
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(11, paramBytes_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static PersonProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static PersonProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static PersonProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static PersonProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static PersonProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static PersonProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static PersonProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static PersonProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static PersonProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static PersonProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(PersonProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements PersonProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DPerson.internal_static_sd_fol_PersonProto_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DPerson.internal_static_sd_fol_PersonProto_fieldAccessorTable;
            }

            // Construct using cywl.test.proto.DPerson.PersonProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getEquipFieldBuilder();
                    getGoodsListFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                age_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                friendID_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000004);
                if (equipBuilder_ == null) {
                    equip_ = GoodsProto.getDefaultInstance();
                } else {
                    equipBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000008);
                if (goodsListBuilder_ == null) {
                    goodsList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000010);
                } else {
                    goodsListBuilder_.clear();
                }
                floatTest_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000020);
                doubleTest_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000040);
                trueTest_ = false;
                bitField0_ = (bitField0_ & ~0x00000080);
                falseTest_ = false;
                bitField0_ = (bitField0_ & ~0x00000100);
                noteList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000200);
                paramBytes_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000400);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PersonProto.getDescriptor();
            }

            public PersonProto getDefaultInstanceForType() {
                return PersonProto.getDefaultInstance();
            }

            public PersonProto build() {
                PersonProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private PersonProto buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                PersonProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public PersonProto buildPartial() {
                PersonProto result = new PersonProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.age_ = age_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    friendID_ = java.util.Collections.unmodifiableList(friendID_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.friendID_ = friendID_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000004;
                }
                if (equipBuilder_ == null) {
                    result.equip_ = equip_;
                } else {
                    result.equip_ = equipBuilder_.build();
                }
                if (goodsListBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) == 0x00000010)) {
                        goodsList_ = java.util.Collections.unmodifiableList(goodsList_);
                        bitField0_ = (bitField0_ & ~0x00000010);
                    }
                    result.goodsList_ = goodsList_;
                } else {
                    result.goodsList_ = goodsListBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.floatTest_ = floatTest_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.doubleTest_ = doubleTest_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.trueTest_ = trueTest_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.falseTest_ = falseTest_;
                if (((bitField0_ & 0x00000200) == 0x00000200)) {
                    noteList_ = new com.google.protobuf.UnmodifiableLazyStringList(
                            noteList_);
                    bitField0_ = (bitField0_ & ~0x00000200);
                }
                result.noteList_ = noteList_;
                if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.paramBytes_ = paramBytes_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PersonProto) {
                    return mergeFrom((PersonProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PersonProto other) {
                if (other == PersonProto.getDefaultInstance()) return this;
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (other.hasAge()) {
                    setAge(other.getAge());
                }
                if (!other.friendID_.isEmpty()) {
                    if (friendID_.isEmpty()) {
                        friendID_ = other.friendID_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureFriendIDIsMutable();
                        friendID_.addAll(other.friendID_);
                    }
                    onChanged();
                }
                if (other.hasEquip()) {
                    mergeEquip(other.getEquip());
                }
                if (goodsListBuilder_ == null) {
                    if (!other.goodsList_.isEmpty()) {
                        if (goodsList_.isEmpty()) {
                            goodsList_ = other.goodsList_;
                            bitField0_ = (bitField0_ & ~0x00000010);
                        } else {
                            ensureGoodsListIsMutable();
                            goodsList_.addAll(other.goodsList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.goodsList_.isEmpty()) {
                        if (goodsListBuilder_.isEmpty()) {
                            goodsListBuilder_.dispose();
                            goodsListBuilder_ = null;
                            goodsList_ = other.goodsList_;
                            bitField0_ = (bitField0_ & ~0x00000010);
                            goodsListBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getGoodsListFieldBuilder() : null;
                        } else {
                            goodsListBuilder_.addAllMessages(other.goodsList_);
                        }
                    }
                }
                if (other.hasFloatTest()) {
                    setFloatTest(other.getFloatTest());
                }
                if (other.hasDoubleTest()) {
                    setDoubleTest(other.getDoubleTest());
                }
                if (other.hasTrueTest()) {
                    setTrueTest(other.getTrueTest());
                }
                if (other.hasFalseTest()) {
                    setFalseTest(other.getFalseTest());
                }
                if (!other.noteList_.isEmpty()) {
                    if (noteList_.isEmpty()) {
                        noteList_ = other.noteList_;
                        bitField0_ = (bitField0_ & ~0x00000200);
                    } else {
                        ensureNoteListIsMutable();
                        noteList_.addAll(other.noteList_);
                    }
                    onChanged();
                }
                if (other.hasParamBytes()) {
                    setParamBytes(other.getParamBytes());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            age_ = input.readSInt32();
                            break;
                        }
                        case 24: {
                            ensureFriendIDIsMutable();
                            friendID_.add(input.readSInt32());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            while (input.getBytesUntilLimit() > 0) {
                                addFriendID(input.readSInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 34: {
                            GoodsProto.Builder subBuilder = GoodsProto.newBuilder();
                            if (hasEquip()) {
                                subBuilder.mergeFrom(getEquip());
                            }
                            input.readMessage(subBuilder, extensionRegistry);
                            setEquip(subBuilder.buildPartial());
                            break;
                        }
                        case 42: {
                            GoodsProto.Builder subBuilder = GoodsProto.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addGoodsList(subBuilder.buildPartial());
                            break;
                        }
                        case 53: {
                            bitField0_ |= 0x00000020;
                            floatTest_ = input.readFloat();
                            break;
                        }
                        case 57: {
                            bitField0_ |= 0x00000040;
                            doubleTest_ = input.readDouble();
                            break;
                        }
                        case 64: {
                            bitField0_ |= 0x00000080;
                            trueTest_ = input.readBool();
                            break;
                        }
                        case 72: {
                            bitField0_ |= 0x00000100;
                            falseTest_ = input.readBool();
                            break;
                        }
                        case 82: {
                            ensureNoteListIsMutable();
                            noteList_.add(input.readBytes());
                            break;
                        }
                        case 90: {
                            bitField0_ |= 0x00000400;
                            paramBytes_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional string name = 1;
            private Object name_ = "";

            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }

            // optional sint32 age = 2;
            private int age_;

            public boolean hasAge() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getAge() {
                return age_;
            }

            public Builder setAge(int value) {
                bitField0_ |= 0x00000002;
                age_ = value;
                onChanged();
                return this;
            }

            public Builder clearAge() {
                bitField0_ = (bitField0_ & ~0x00000002);
                age_ = 0;
                onChanged();
                return this;
            }

            // repeated sint32 friendID = 3 [packed = true];
            private java.util.List<Integer> friendID_ = java.util.Collections.emptyList();
            ;

            private void ensureFriendIDIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    friendID_ = new java.util.ArrayList<Integer>(friendID_);
                    bitField0_ |= 0x00000004;
                }
            }

            public java.util.List<Integer>
            getFriendIDList() {
                return java.util.Collections.unmodifiableList(friendID_);
            }

            public int getFriendIDCount() {
                return friendID_.size();
            }

            public int getFriendID(int index) {
                return friendID_.get(index);
            }

            public Builder setFriendID(
                    int index, int value) {
                ensureFriendIDIsMutable();
                friendID_.set(index, value);
                onChanged();
                return this;
            }

            public Builder addFriendID(int value) {
                ensureFriendIDIsMutable();
                friendID_.add(value);
                onChanged();
                return this;
            }

            public Builder addAllFriendID(
                    Iterable<? extends Integer> values) {
                ensureFriendIDIsMutable();
                super.addAll(values, friendID_);
                onChanged();
                return this;
            }

            public Builder clearFriendID() {
                friendID_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            // optional .sd.fol.GoodsProto equip = 4;
            private GoodsProto equip_ = GoodsProto.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder> equipBuilder_;

            public boolean hasEquip() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public GoodsProto getEquip() {
                if (equipBuilder_ == null) {
                    return equip_;
                } else {
                    return equipBuilder_.getMessage();
                }
            }

            public Builder setEquip(GoodsProto value) {
                if (equipBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    equip_ = value;
                    onChanged();
                } else {
                    equipBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            public Builder setEquip(
                    GoodsProto.Builder builderForValue) {
                if (equipBuilder_ == null) {
                    equip_ = builderForValue.build();
                    onChanged();
                } else {
                    equipBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            public Builder mergeEquip(GoodsProto value) {
                if (equipBuilder_ == null) {
                    if (((bitField0_ & 0x00000008) == 0x00000008) &&
                            equip_ != GoodsProto.getDefaultInstance()) {
                        equip_ =
                                GoodsProto.newBuilder(equip_).mergeFrom(value).buildPartial();
                    } else {
                        equip_ = value;
                    }
                    onChanged();
                } else {
                    equipBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000008;
                return this;
            }

            public Builder clearEquip() {
                if (equipBuilder_ == null) {
                    equip_ = GoodsProto.getDefaultInstance();
                    onChanged();
                } else {
                    equipBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public GoodsProto.Builder getEquipBuilder() {
                bitField0_ |= 0x00000008;
                onChanged();
                return getEquipFieldBuilder().getBuilder();
            }

            public GoodsProtoOrBuilder getEquipOrBuilder() {
                if (equipBuilder_ != null) {
                    return equipBuilder_.getMessageOrBuilder();
                } else {
                    return equip_;
                }
            }

            private com.google.protobuf.SingleFieldBuilder<
                    GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder>
            getEquipFieldBuilder() {
                if (equipBuilder_ == null) {
                    equipBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder>(
                            equip_,
                            getParentForChildren(),
                            isClean());
                    equip_ = null;
                }
                return equipBuilder_;
            }

            // repeated .sd.fol.GoodsProto goodsList = 5;
            private java.util.List<GoodsProto> goodsList_ =
                    java.util.Collections.emptyList();

            private void ensureGoodsListIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    goodsList_ = new java.util.ArrayList<GoodsProto>(goodsList_);
                    bitField0_ |= 0x00000010;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder> goodsListBuilder_;

            public java.util.List<GoodsProto> getGoodsListList() {
                if (goodsListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(goodsList_);
                } else {
                    return goodsListBuilder_.getMessageList();
                }
            }

            public int getGoodsListCount() {
                if (goodsListBuilder_ == null) {
                    return goodsList_.size();
                } else {
                    return goodsListBuilder_.getCount();
                }
            }

            public GoodsProto getGoodsList(int index) {
                if (goodsListBuilder_ == null) {
                    return goodsList_.get(index);
                } else {
                    return goodsListBuilder_.getMessage(index);
                }
            }

            public Builder setGoodsList(
                    int index, GoodsProto value) {
                if (goodsListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoodsListIsMutable();
                    goodsList_.set(index, value);
                    onChanged();
                } else {
                    goodsListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setGoodsList(
                    int index, GoodsProto.Builder builderForValue) {
                if (goodsListBuilder_ == null) {
                    ensureGoodsListIsMutable();
                    goodsList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    goodsListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addGoodsList(GoodsProto value) {
                if (goodsListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoodsListIsMutable();
                    goodsList_.add(value);
                    onChanged();
                } else {
                    goodsListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addGoodsList(
                    int index, GoodsProto value) {
                if (goodsListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoodsListIsMutable();
                    goodsList_.add(index, value);
                    onChanged();
                } else {
                    goodsListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addGoodsList(
                    GoodsProto.Builder builderForValue) {
                if (goodsListBuilder_ == null) {
                    ensureGoodsListIsMutable();
                    goodsList_.add(builderForValue.build());
                    onChanged();
                } else {
                    goodsListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addGoodsList(
                    int index, GoodsProto.Builder builderForValue) {
                if (goodsListBuilder_ == null) {
                    ensureGoodsListIsMutable();
                    goodsList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    goodsListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllGoodsList(
                    Iterable<? extends GoodsProto> values) {
                if (goodsListBuilder_ == null) {
                    ensureGoodsListIsMutable();
                    super.addAll(values, goodsList_);
                    onChanged();
                } else {
                    goodsListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearGoodsList() {
                if (goodsListBuilder_ == null) {
                    goodsList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000010);
                    onChanged();
                } else {
                    goodsListBuilder_.clear();
                }
                return this;
            }

            public Builder removeGoodsList(int index) {
                if (goodsListBuilder_ == null) {
                    ensureGoodsListIsMutable();
                    goodsList_.remove(index);
                    onChanged();
                } else {
                    goodsListBuilder_.remove(index);
                }
                return this;
            }

            public GoodsProto.Builder getGoodsListBuilder(
                    int index) {
                return getGoodsListFieldBuilder().getBuilder(index);
            }

            public GoodsProtoOrBuilder getGoodsListOrBuilder(
                    int index) {
                if (goodsListBuilder_ == null) {
                    return goodsList_.get(index);
                } else {
                    return goodsListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends GoodsProtoOrBuilder>
            getGoodsListOrBuilderList() {
                if (goodsListBuilder_ != null) {
                    return goodsListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(goodsList_);
                }
            }

            public GoodsProto.Builder addGoodsListBuilder() {
                return getGoodsListFieldBuilder().addBuilder(
                        GoodsProto.getDefaultInstance());
            }

            public GoodsProto.Builder addGoodsListBuilder(
                    int index) {
                return getGoodsListFieldBuilder().addBuilder(
                        index, GoodsProto.getDefaultInstance());
            }

            public java.util.List<GoodsProto.Builder>
            getGoodsListBuilderList() {
                return getGoodsListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder>
            getGoodsListFieldBuilder() {
                if (goodsListBuilder_ == null) {
                    goodsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            GoodsProto, GoodsProto.Builder, GoodsProtoOrBuilder>(
                            goodsList_,
                            ((bitField0_ & 0x00000010) == 0x00000010),
                            getParentForChildren(),
                            isClean());
                    goodsList_ = null;
                }
                return goodsListBuilder_;
            }

            // optional float floatTest = 6;
            private float floatTest_;

            public boolean hasFloatTest() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public float getFloatTest() {
                return floatTest_;
            }

            public Builder setFloatTest(float value) {
                bitField0_ |= 0x00000020;
                floatTest_ = value;
                onChanged();
                return this;
            }

            public Builder clearFloatTest() {
                bitField0_ = (bitField0_ & ~0x00000020);
                floatTest_ = 0F;
                onChanged();
                return this;
            }

            // optional double doubleTest = 7;
            private double doubleTest_;

            public boolean hasDoubleTest() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public double getDoubleTest() {
                return doubleTest_;
            }

            public Builder setDoubleTest(double value) {
                bitField0_ |= 0x00000040;
                doubleTest_ = value;
                onChanged();
                return this;
            }

            public Builder clearDoubleTest() {
                bitField0_ = (bitField0_ & ~0x00000040);
                doubleTest_ = 0D;
                onChanged();
                return this;
            }

            // optional bool trueTest = 8;
            private boolean trueTest_;

            public boolean hasTrueTest() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            public boolean getTrueTest() {
                return trueTest_;
            }

            public Builder setTrueTest(boolean value) {
                bitField0_ |= 0x00000080;
                trueTest_ = value;
                onChanged();
                return this;
            }

            public Builder clearTrueTest() {
                bitField0_ = (bitField0_ & ~0x00000080);
                trueTest_ = false;
                onChanged();
                return this;
            }

            // optional bool falseTest = 9;
            private boolean falseTest_;

            public boolean hasFalseTest() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }

            public boolean getFalseTest() {
                return falseTest_;
            }

            public Builder setFalseTest(boolean value) {
                bitField0_ |= 0x00000100;
                falseTest_ = value;
                onChanged();
                return this;
            }

            public Builder clearFalseTest() {
                bitField0_ = (bitField0_ & ~0x00000100);
                falseTest_ = false;
                onChanged();
                return this;
            }

            // repeated string noteList = 10;
            private com.google.protobuf.LazyStringList noteList_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureNoteListIsMutable() {
                if (!((bitField0_ & 0x00000200) == 0x00000200)) {
                    noteList_ = new com.google.protobuf.LazyStringArrayList(noteList_);
                    bitField0_ |= 0x00000200;
                }
            }

            public java.util.List<String>
            getNoteListList() {
                return java.util.Collections.unmodifiableList(noteList_);
            }

            public int getNoteListCount() {
                return noteList_.size();
            }

            public String getNoteList(int index) {
                return noteList_.get(index);
            }

            public Builder setNoteList(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNoteListIsMutable();
                noteList_.set(index, value);
                onChanged();
                return this;
            }

            public Builder addNoteList(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureNoteListIsMutable();
                noteList_.add(value);
                onChanged();
                return this;
            }

            public Builder addAllNoteList(
                    Iterable<String> values) {
                ensureNoteListIsMutable();
                super.addAll(values, noteList_);
                onChanged();
                return this;
            }

            public Builder clearNoteList() {
                noteList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000200);
                onChanged();
                return this;
            }

            void addNoteList(com.google.protobuf.ByteString value) {
                ensureNoteListIsMutable();
                noteList_.add(value);
                onChanged();
            }

            // optional bytes paramBytes = 11;
            private com.google.protobuf.ByteString paramBytes_ = com.google.protobuf.ByteString.EMPTY;

            public boolean hasParamBytes() {
                return ((bitField0_ & 0x00000400) == 0x00000400);
            }

            public com.google.protobuf.ByteString getParamBytes() {
                return paramBytes_;
            }

            public Builder setParamBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000400;
                paramBytes_ = value;
                onChanged();
                return this;
            }

            public Builder clearParamBytes() {
                bitField0_ = (bitField0_ & ~0x00000400);
                paramBytes_ = getDefaultInstance().getParamBytes();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:sd.fol.PersonProto)
        }

        static {
            defaultInstance = new PersonProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:sd.fol.PersonProto)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_sd_fol_GoodsProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_sd_fol_GoodsProto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_sd_fol_PersonProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_sd_fol_PersonProto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\022test/DPerson.proto\022\006sd.fol\"(\n\nGoodsPro" +
                        "to\022\014\n\004name\030\001 \001(\t\022\014\n\004desc\030\002 \001(\t\"\372\001\n\013Perso" +
                        "nProto\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\021\022\024\n\010fri" +
                        "endID\030\003 \003(\021B\002\020\001\022!\n\005equip\030\004 \001(\0132\022.sd.fol." +
                        "GoodsProto\022%\n\tgoodsList\030\005 \003(\0132\022.sd.fol.G" +
                        "oodsProto\022\021\n\tfloatTest\030\006 \001(\002\022\022\n\ndoubleTe" +
                        "st\030\007 \001(\001\022\020\n\010trueTest\030\010 \001(\010\022\021\n\tfalseTest\030" +
                        "\t \001(\010\022\020\n\010noteList\030\n \003(\t\022\022\n\nparamBytes\030\013 " +
                        "\001(\014B\021\n\017cywl.test.proto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_sd_fol_GoodsProto_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_sd_fol_GoodsProto_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_sd_fol_GoodsProto_descriptor,
                                new String[]{"Name", "Desc",},
                                GoodsProto.class,
                                GoodsProto.Builder.class);
                        internal_static_sd_fol_PersonProto_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_sd_fol_PersonProto_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_sd_fol_PersonProto_descriptor,
                                new String[]{"Name", "Age", "FriendID", "Equip", "GoodsList", "FloatTest", "DoubleTest", "TrueTest", "FalseTest", "NoteList", "ParamBytes",},
                                PersonProto.class,
                                PersonProto.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
