// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/DTestDTO.proto

package cywl.test.proto;

public final class DTestDTO {
    private DTestDTO() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface TestDTOProtoOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional int32 age = 1;
        boolean hasAge();

        int getAge();

        // optional string name = 2;
        boolean hasName();

        String getName();

        // repeated string strList = 3;
        java.util.List<String> getStrListList();

        int getStrListCount();

        String getStrList(int index);

        // repeated int32 idList = 4 [packed = true];
        java.util.List<Integer> getIdListList();

        int getIdListCount();

        int getIdList(int index);

        // optional .sd.fol.DataProto data = 5;
        boolean hasData();

        DataProto getData();

        DataProtoOrBuilder getDataOrBuilder();

        // repeated .sd.fol.DataProto dataList = 6;
        java.util.List<DataProto>
        getDataListList();

        DataProto getDataList(int index);

        int getDataListCount();

        java.util.List<? extends DataProtoOrBuilder>
        getDataListOrBuilderList();

        DataProtoOrBuilder getDataListOrBuilder(
                int index);
    }

    public static final class TestDTOProto extends
            com.google.protobuf.GeneratedMessage
            implements TestDTOProtoOrBuilder {
        // Use TestDTOProto.newBuilder() to construct.
        private TestDTOProto(Builder builder) {
            super(builder);
        }

        private TestDTOProto(boolean noInit) {
        }

        private static final TestDTOProto defaultInstance;

        public static TestDTOProto getDefaultInstance() {
            return defaultInstance;
        }

        public TestDTOProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DTestDTO.internal_static_sd_fol_TestDTOProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DTestDTO.internal_static_sd_fol_TestDTOProto_fieldAccessorTable;
        }

        private int bitField0_;
        // optional int32 age = 1;
        public static final int AGE_FIELD_NUMBER = 1;
        private int age_;

        public boolean hasAge() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getAge() {
            return age_;
        }

        // optional string name = 2;
        public static final int NAME_FIELD_NUMBER = 2;
        private Object name_;

        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated string strList = 3;
        public static final int STRLIST_FIELD_NUMBER = 3;
        private com.google.protobuf.LazyStringList strList_;

        public java.util.List<String>
        getStrListList() {
            return strList_;
        }

        public int getStrListCount() {
            return strList_.size();
        }

        public String getStrList(int index) {
            return strList_.get(index);
        }

        // repeated int32 idList = 4 [packed = true];
        public static final int IDLIST_FIELD_NUMBER = 4;
        private java.util.List<Integer> idList_;

        public java.util.List<Integer>
        getIdListList() {
            return idList_;
        }

        public int getIdListCount() {
            return idList_.size();
        }

        public int getIdList(int index) {
            return idList_.get(index);
        }

        private int idListMemoizedSerializedSize = -1;

        // optional .sd.fol.DataProto data = 5;
        public static final int DATA_FIELD_NUMBER = 5;
        private DataProto data_;

        public boolean hasData() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public DataProto getData() {
            return data_;
        }

        public DataProtoOrBuilder getDataOrBuilder() {
            return data_;
        }

        // repeated .sd.fol.DataProto dataList = 6;
        public static final int DATALIST_FIELD_NUMBER = 6;
        private java.util.List<DataProto> dataList_;

        public java.util.List<DataProto> getDataListList() {
            return dataList_;
        }

        public java.util.List<? extends DataProtoOrBuilder>
        getDataListOrBuilderList() {
            return dataList_;
        }

        public int getDataListCount() {
            return dataList_.size();
        }

        public DataProto getDataList(int index) {
            return dataList_.get(index);
        }

        public DataProtoOrBuilder getDataListOrBuilder(
                int index) {
            return dataList_.get(index);
        }

        private void initFields() {
            age_ = 0;
            name_ = "";
            strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            idList_ = java.util.Collections.emptyList();
            ;
            data_ = DataProto.getDefaultInstance();
            dataList_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, age_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getNameBytes());
            }
            for (int i = 0; i < strList_.size(); i++) {
                output.writeBytes(3, strList_.getByteString(i));
            }
            if (getIdListList().size() > 0) {
                output.writeRawVarint32(34);
                output.writeRawVarint32(idListMemoizedSerializedSize);
            }
            for (int i = 0; i < idList_.size(); i++) {
                output.writeInt32NoTag(idList_.get(i));
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeMessage(5, data_);
            }
            for (int i = 0; i < dataList_.size(); i++) {
                output.writeMessage(6, dataList_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, age_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getNameBytes());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < strList_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(strList_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getStrListList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < idList_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(idList_.get(i));
                }
                size += dataSize;
                if (!getIdListList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                idListMemoizedSerializedSize = dataSize;
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, data_);
            }
            for (int i = 0; i < dataList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, dataList_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static TestDTOProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static TestDTOProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static TestDTOProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static TestDTOProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static TestDTOProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static TestDTOProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static TestDTOProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static TestDTOProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static TestDTOProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static TestDTOProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(TestDTOProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements TestDTOProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DTestDTO.internal_static_sd_fol_TestDTOProto_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DTestDTO.internal_static_sd_fol_TestDTOProto_fieldAccessorTable;
            }

            // Construct using cywl.test.proto.DTestDTO.TestDTOProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getDataFieldBuilder();
                    getDataListFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                age_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                idList_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000008);
                if (dataBuilder_ == null) {
                    data_ = DataProto.getDefaultInstance();
                } else {
                    dataBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000010);
                if (dataListBuilder_ == null) {
                    dataList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                } else {
                    dataListBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestDTOProto.getDescriptor();
            }

            public TestDTOProto getDefaultInstanceForType() {
                return TestDTOProto.getDefaultInstance();
            }

            public TestDTOProto build() {
                TestDTOProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private TestDTOProto buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                TestDTOProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public TestDTOProto buildPartial() {
                TestDTOProto result = new TestDTOProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.age_ = age_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    strList_ = new com.google.protobuf.UnmodifiableLazyStringList(
                            strList_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.strList_ = strList_;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    idList_ = java.util.Collections.unmodifiableList(idList_);
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.idList_ = idList_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000004;
                }
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                } else {
                    result.data_ = dataBuilder_.build();
                }
                if (dataListBuilder_ == null) {
                    if (((bitField0_ & 0x00000020) == 0x00000020)) {
                        dataList_ = java.util.Collections.unmodifiableList(dataList_);
                        bitField0_ = (bitField0_ & ~0x00000020);
                    }
                    result.dataList_ = dataList_;
                } else {
                    result.dataList_ = dataListBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestDTOProto) {
                    return mergeFrom((TestDTOProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestDTOProto other) {
                if (other == TestDTOProto.getDefaultInstance()) return this;
                if (other.hasAge()) {
                    setAge(other.getAge());
                }
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (!other.strList_.isEmpty()) {
                    if (strList_.isEmpty()) {
                        strList_ = other.strList_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureStrListIsMutable();
                        strList_.addAll(other.strList_);
                    }
                    onChanged();
                }
                if (!other.idList_.isEmpty()) {
                    if (idList_.isEmpty()) {
                        idList_ = other.idList_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureIdListIsMutable();
                        idList_.addAll(other.idList_);
                    }
                    onChanged();
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                if (dataListBuilder_ == null) {
                    if (!other.dataList_.isEmpty()) {
                        if (dataList_.isEmpty()) {
                            dataList_ = other.dataList_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                        } else {
                            ensureDataListIsMutable();
                            dataList_.addAll(other.dataList_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.dataList_.isEmpty()) {
                        if (dataListBuilder_.isEmpty()) {
                            dataListBuilder_.dispose();
                            dataListBuilder_ = null;
                            dataList_ = other.dataList_;
                            bitField0_ = (bitField0_ & ~0x00000020);
                            dataListBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getDataListFieldBuilder() : null;
                        } else {
                            dataListBuilder_.addAllMessages(other.dataList_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            age_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            name_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            ensureStrListIsMutable();
                            strList_.add(input.readBytes());
                            break;
                        }
                        case 32: {
                            ensureIdListIsMutable();
                            idList_.add(input.readInt32());
                            break;
                        }
                        case 34: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            while (input.getBytesUntilLimit() > 0) {
                                addIdList(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 42: {
                            DataProto.Builder subBuilder = DataProto.newBuilder();
                            if (hasData()) {
                                subBuilder.mergeFrom(getData());
                            }
                            input.readMessage(subBuilder, extensionRegistry);
                            setData(subBuilder.buildPartial());
                            break;
                        }
                        case 50: {
                            DataProto.Builder subBuilder = DataProto.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addDataList(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional int32 age = 1;
            private int age_;

            public boolean hasAge() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getAge() {
                return age_;
            }

            public Builder setAge(int value) {
                bitField0_ |= 0x00000001;
                age_ = value;
                onChanged();
                return this;
            }

            public Builder clearAge() {
                bitField0_ = (bitField0_ & ~0x00000001);
                age_ = 0;
                onChanged();
                return this;
            }

            // optional string name = 2;
            private Object name_ = "";

            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
            }

            // repeated string strList = 3;
            private com.google.protobuf.LazyStringList strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureStrListIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    strList_ = new com.google.protobuf.LazyStringArrayList(strList_);
                    bitField0_ |= 0x00000004;
                }
            }

            public java.util.List<String>
            getStrListList() {
                return java.util.Collections.unmodifiableList(strList_);
            }

            public int getStrListCount() {
                return strList_.size();
            }

            public String getStrList(int index) {
                return strList_.get(index);
            }

            public Builder setStrList(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStrListIsMutable();
                strList_.set(index, value);
                onChanged();
                return this;
            }

            public Builder addStrList(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStrListIsMutable();
                strList_.add(value);
                onChanged();
                return this;
            }

            public Builder addAllStrList(
                    Iterable<String> values) {
                ensureStrListIsMutable();
                super.addAll(values, strList_);
                onChanged();
                return this;
            }

            public Builder clearStrList() {
                strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            void addStrList(com.google.protobuf.ByteString value) {
                ensureStrListIsMutable();
                strList_.add(value);
                onChanged();
            }

            // repeated int32 idList = 4 [packed = true];
            private java.util.List<Integer> idList_ = java.util.Collections.emptyList();
            ;

            private void ensureIdListIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    idList_ = new java.util.ArrayList<Integer>(idList_);
                    bitField0_ |= 0x00000008;
                }
            }

            public java.util.List<Integer>
            getIdListList() {
                return java.util.Collections.unmodifiableList(idList_);
            }

            public int getIdListCount() {
                return idList_.size();
            }

            public int getIdList(int index) {
                return idList_.get(index);
            }

            public Builder setIdList(
                    int index, int value) {
                ensureIdListIsMutable();
                idList_.set(index, value);
                onChanged();
                return this;
            }

            public Builder addIdList(int value) {
                ensureIdListIsMutable();
                idList_.add(value);
                onChanged();
                return this;
            }

            public Builder addAllIdList(
                    Iterable<? extends Integer> values) {
                ensureIdListIsMutable();
                super.addAll(values, idList_);
                onChanged();
                return this;
            }

            public Builder clearIdList() {
                idList_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            // optional .sd.fol.DataProto data = 5;
            private DataProto data_ = DataProto.getDefaultInstance();
            private com.google.protobuf.SingleFieldBuilder<
                    DataProto, DataProto.Builder, DataProtoOrBuilder> dataBuilder_;

            public boolean hasData() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public DataProto getData() {
                if (dataBuilder_ == null) {
                    return data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            public Builder setData(DataProto value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                } else {
                    dataBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            public Builder setData(
                    DataProto.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            public Builder mergeData(DataProto value) {
                if (dataBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) == 0x00000010) &&
                            data_ != DataProto.getDefaultInstance()) {
                        data_ =
                                DataProto.newBuilder(data_).mergeFrom(value).buildPartial();
                    } else {
                        data_ = value;
                    }
                    onChanged();
                } else {
                    dataBuilder_.mergeFrom(value);
                }
                bitField0_ |= 0x00000010;
                return this;
            }

            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = DataProto.getDefaultInstance();
                    onChanged();
                } else {
                    dataBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public DataProto.Builder getDataBuilder() {
                bitField0_ |= 0x00000010;
                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            public DataProtoOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_;
                }
            }

            private com.google.protobuf.SingleFieldBuilder<
                    DataProto, DataProto.Builder, DataProtoOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            DataProto, DataProto.Builder, DataProtoOrBuilder>(
                            data_,
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            // repeated .sd.fol.DataProto dataList = 6;
            private java.util.List<DataProto> dataList_ =
                    java.util.Collections.emptyList();

            private void ensureDataListIsMutable() {
                if (!((bitField0_ & 0x00000020) == 0x00000020)) {
                    dataList_ = new java.util.ArrayList<DataProto>(dataList_);
                    bitField0_ |= 0x00000020;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    DataProto, DataProto.Builder, DataProtoOrBuilder> dataListBuilder_;

            public java.util.List<DataProto> getDataListList() {
                if (dataListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(dataList_);
                } else {
                    return dataListBuilder_.getMessageList();
                }
            }

            public int getDataListCount() {
                if (dataListBuilder_ == null) {
                    return dataList_.size();
                } else {
                    return dataListBuilder_.getCount();
                }
            }

            public DataProto getDataList(int index) {
                if (dataListBuilder_ == null) {
                    return dataList_.get(index);
                } else {
                    return dataListBuilder_.getMessage(index);
                }
            }

            public Builder setDataList(
                    int index, DataProto value) {
                if (dataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDataListIsMutable();
                    dataList_.set(index, value);
                    onChanged();
                } else {
                    dataListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setDataList(
                    int index, DataProto.Builder builderForValue) {
                if (dataListBuilder_ == null) {
                    ensureDataListIsMutable();
                    dataList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    dataListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addDataList(DataProto value) {
                if (dataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDataListIsMutable();
                    dataList_.add(value);
                    onChanged();
                } else {
                    dataListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addDataList(
                    int index, DataProto value) {
                if (dataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDataListIsMutable();
                    dataList_.add(index, value);
                    onChanged();
                } else {
                    dataListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addDataList(
                    DataProto.Builder builderForValue) {
                if (dataListBuilder_ == null) {
                    ensureDataListIsMutable();
                    dataList_.add(builderForValue.build());
                    onChanged();
                } else {
                    dataListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addDataList(
                    int index, DataProto.Builder builderForValue) {
                if (dataListBuilder_ == null) {
                    ensureDataListIsMutable();
                    dataList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    dataListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllDataList(
                    Iterable<? extends DataProto> values) {
                if (dataListBuilder_ == null) {
                    ensureDataListIsMutable();
                    super.addAll(values, dataList_);
                    onChanged();
                } else {
                    dataListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearDataList() {
                if (dataListBuilder_ == null) {
                    dataList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000020);
                    onChanged();
                } else {
                    dataListBuilder_.clear();
                }
                return this;
            }

            public Builder removeDataList(int index) {
                if (dataListBuilder_ == null) {
                    ensureDataListIsMutable();
                    dataList_.remove(index);
                    onChanged();
                } else {
                    dataListBuilder_.remove(index);
                }
                return this;
            }

            public DataProto.Builder getDataListBuilder(
                    int index) {
                return getDataListFieldBuilder().getBuilder(index);
            }

            public DataProtoOrBuilder getDataListOrBuilder(
                    int index) {
                if (dataListBuilder_ == null) {
                    return dataList_.get(index);
                } else {
                    return dataListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends DataProtoOrBuilder>
            getDataListOrBuilderList() {
                if (dataListBuilder_ != null) {
                    return dataListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(dataList_);
                }
            }

            public DataProto.Builder addDataListBuilder() {
                return getDataListFieldBuilder().addBuilder(
                        DataProto.getDefaultInstance());
            }

            public DataProto.Builder addDataListBuilder(
                    int index) {
                return getDataListFieldBuilder().addBuilder(
                        index, DataProto.getDefaultInstance());
            }

            public java.util.List<DataProto.Builder>
            getDataListBuilderList() {
                return getDataListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    DataProto, DataProto.Builder, DataProtoOrBuilder>
            getDataListFieldBuilder() {
                if (dataListBuilder_ == null) {
                    dataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            DataProto, DataProto.Builder, DataProtoOrBuilder>(
                            dataList_,
                            ((bitField0_ & 0x00000020) == 0x00000020),
                            getParentForChildren(),
                            isClean());
                    dataList_ = null;
                }
                return dataListBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:sd.fol.TestDTOProto)
        }

        static {
            defaultInstance = new TestDTOProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:sd.fol.TestDTOProto)
    }

    public interface DataProtoOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string data = 1;
        boolean hasData();

        String getData();

        // optional string data1 = 1001;
        boolean hasData1();

        String getData1();

        // optional string data2 = 2001;
        boolean hasData2();

        String getData2();
    }

    public static final class DataProto extends
            com.google.protobuf.GeneratedMessage
            implements DataProtoOrBuilder {
        // Use DataProto.newBuilder() to construct.
        private DataProto(Builder builder) {
            super(builder);
        }

        private DataProto(boolean noInit) {
        }

        private static final DataProto defaultInstance;

        public static DataProto getDefaultInstance() {
            return defaultInstance;
        }

        public DataProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DTestDTO.internal_static_sd_fol_DataProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DTestDTO.internal_static_sd_fol_DataProto_fieldAccessorTable;
        }

        private int bitField0_;
        // optional string data = 1;
        public static final int DATA_FIELD_NUMBER = 1;
        private Object data_;

        public boolean hasData() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getData() {
            Object ref = data_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    data_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getDataBytes() {
            Object ref = data_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                data_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string data1 = 1001;
        public static final int DATA1_FIELD_NUMBER = 1001;
        private Object data1_;

        public boolean hasData1() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getData1() {
            Object ref = data1_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    data1_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getData1Bytes() {
            Object ref = data1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                data1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string data2 = 2001;
        public static final int DATA2_FIELD_NUMBER = 2001;
        private Object data2_;

        public boolean hasData2() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public String getData2() {
            Object ref = data2_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    data2_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getData2Bytes() {
            Object ref = data2_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                data2_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            data_ = "";
            data1_ = "";
            data2_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getDataBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(1001, getData1Bytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(2001, getData2Bytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getDataBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1001, getData1Bytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2001, getData2Bytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static DataProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static DataProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static DataProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static DataProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static DataProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static DataProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static DataProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static DataProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static DataProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static DataProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(DataProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements DataProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DTestDTO.internal_static_sd_fol_DataProto_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DTestDTO.internal_static_sd_fol_DataProto_fieldAccessorTable;
            }

            // Construct using cywl.test.proto.DTestDTO.DataProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                data_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                data1_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                data2_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DataProto.getDescriptor();
            }

            public DataProto getDefaultInstanceForType() {
                return DataProto.getDefaultInstance();
            }

            public DataProto build() {
                DataProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private DataProto buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                DataProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public DataProto buildPartial() {
                DataProto result = new DataProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.data_ = data_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.data1_ = data1_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.data2_ = data2_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DataProto) {
                    return mergeFrom((DataProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DataProto other) {
                if (other == DataProto.getDefaultInstance()) return this;
                if (other.hasData()) {
                    setData(other.getData());
                }
                if (other.hasData1()) {
                    setData1(other.getData1());
                }
                if (other.hasData2()) {
                    setData2(other.getData2());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            data_ = input.readBytes();
                            break;
                        }
                        case 8010: {
                            bitField0_ |= 0x00000002;
                            data1_ = input.readBytes();
                            break;
                        }
                        case 16010: {
                            bitField0_ |= 0x00000004;
                            data2_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional string data = 1;
            private Object data_ = "";

            public boolean hasData() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getData() {
                Object ref = data_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    data_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setData(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                data_ = value;
                onChanged();
                return this;
            }

            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000001);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            void setData(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                data_ = value;
                onChanged();
            }

            // optional string data1 = 1001;
            private Object data1_ = "";

            public boolean hasData1() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getData1() {
                Object ref = data1_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    data1_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setData1(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                data1_ = value;
                onChanged();
                return this;
            }

            public Builder clearData1() {
                bitField0_ = (bitField0_ & ~0x00000002);
                data1_ = getDefaultInstance().getData1();
                onChanged();
                return this;
            }

            void setData1(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                data1_ = value;
                onChanged();
            }

            // optional string data2 = 2001;
            private Object data2_ = "";

            public boolean hasData2() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public String getData2() {
                Object ref = data2_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    data2_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setData2(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                data2_ = value;
                onChanged();
                return this;
            }

            public Builder clearData2() {
                bitField0_ = (bitField0_ & ~0x00000004);
                data2_ = getDefaultInstance().getData2();
                onChanged();
                return this;
            }

            void setData2(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000004;
                data2_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:sd.fol.DataProto)
        }

        static {
            defaultInstance = new DataProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:sd.fol.DataProto)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_sd_fol_TestDTOProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_sd_fol_TestDTOProto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_sd_fol_DataProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_sd_fol_DataProto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\023test/DTestDTO.proto\022\006sd.fol\"\224\001\n\014TestDT" +
                        "OProto\022\013\n\003age\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007str" +
                        "List\030\003 \003(\t\022\022\n\006idList\030\004 \003(\005B\002\020\001\022\037\n\004data\030\005" +
                        " \001(\0132\021.sd.fol.DataProto\022#\n\010dataList\030\006 \003(" +
                        "\0132\021.sd.fol.DataProto\"9\n\tDataProto\022\014\n\004dat" +
                        "a\030\001 \001(\t\022\016\n\005data1\030\351\007 \001(\t\022\016\n\005data2\030\321\017 \001(\tB" +
                        "\021\n\017cywl.test.proto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_sd_fol_TestDTOProto_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_sd_fol_TestDTOProto_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_sd_fol_TestDTOProto_descriptor,
                                new String[]{"Age", "Name", "StrList", "IdList", "Data", "DataList",},
                                TestDTOProto.class,
                                TestDTOProto.Builder.class);
                        internal_static_sd_fol_DataProto_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_sd_fol_DataProto_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_sd_fol_DataProto_descriptor,
                                new String[]{"Data", "Data1", "Data2",},
                                DataProto.class,
                                DataProto.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
