tny:
  app:
    server-id: 1
    name: GatewayApp
    app-type: gateway
    scope-type: online
  net:
    bootstrap:
      network:
        server:
          name: game-server
          bind-address: 127.0.0.1:16800,127.0.0.1:16801
          channel:
            #            maker:
            #              pipeline-chains:
            #                - readIdlePipelineChain
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
              message-relay-strategy: controllerRelayStrategy
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            tunnel-factory: "localRelayTunnelFactory"
            message-handler: "relayMessageHandler"
      relay:
        client:
          channel:
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
    relay:
      cluster:
        serve-clusters:
          - id: "GameServer"
            link-connection-size: 10
            instances:
              - id: 1
                url: tcp://127.0.0.1:15800
      router:
        fixed-message-router:
          serve-name: "GameServer"
    command:
      processor:
        disruptor:
          setting:
            enable: true
            wait-strategy: blocking
            threads: 4
    endpoint:
      session-keeper:
        name: user
        offline-close-delay: 1000
        offline-max-size: 1000

  data:
    object-storage:
      async-storage:
        enable: false

