tny:
  app:
    name: GameClientApp
    app-type: game
    scope-type: online
    scan-packages: com.tny.game.net.demo,com.tny.game.net,com.tny.game.starter
  net:
    client:
      game-client:
        channel:
          idle-timeout: 360000
        encoder:
          security-keys:
            - abcdefghijklmn
            - opqrstuvwxyz
        decoder:
          security-keys:
            - abcdefghijklmn
            - opqrstuvwxyz
    command-task-processor:
      default:
        threads: 10