tny:
  app:
    name: GameClientApp
    app-type: game
    scope-type: online
  net:
    bootstrap:
      network:
        client:
          channel:
            encoder:
              body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            decoder:
              body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
    command:
      processor:
        disruptor:
          setting:
            enable: true
            wait-strategy: blocking
            threads: 4



