tny:
  app:
    server-id: 1
    name: GatewayApp
    app-type: gateway-service
    scope-type: online
  net:
    bootstrap:
      network:
        server:
          name: game-service
          bind-address: 127.0.0.1:17800
          channel:
            #            maker:
            #              pipeline-chains:
            #                - readIdlePipelineChain
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
              message-relay-strategy: controllerRelayStrategy
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            tunnel-factory: "relayTunnelFactory"
            message-handler: "relayMessageHandler"
      relay:
        client:
          channel:
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
    relay:
      clusters:
        - service: "game-service"
          discovery: false
          connection-size: 1
          serve-nodes:
            - id: 1
              url: tcp://127.0.0.1:15800
      router:
        fixed-message-router:
          service: "game-service"
    session:
      session-keeper:
        name: _user
        offline-close-delay: 1000
        offline-max-size: 1000

  data:
    enable: false
    object-storage:
      async-storage:
        enable: false

