tny:
  app:
    name: GameServerApp
    app-type: game
    scope-type: online
  net:
    bootstrap:
      relay:
        server:
          name: game-server
          bind-address: 127.0.0.1:15800
          channel:
            #            maker:
            #              pipeline-chains:
            #                - readIdlePipelineChain
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
    pipeline:
      read-idle-pipeline-chain:
        idle-timeout: 18000
    command:
      processor:
        disruptor:
          setting:
            enable: true
            wait-strategy: blocking
            threads: 4
    endpoint:
      session-keeper:
        name: user
        offline-close-delay: 1000
        offline-max-size: 1000

  data:
    object-storage:
      async-storage:
        enable: false

