spring:
  redis:
    host: '${r2.redis.host:127.0.0.1}'
    password: '${r2.redis.password:tNbrH3NSErGd}'
    port: '${r2.redis.post:6379}'
    database: '${r2.redis.db:9}'

tny:
  app:
    name: GameClientApp
    app-type: game
    scope-type: online
  net:
    bootstrap:
      network:
        client:
          channel:
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
    command:
      processor:
        disruptor:
          setting:
            enable: true
            wait-strategy: blocking
            threads: 4
  data:
    storage:
      enable: false


