tny:
  app:
    name: GameServerApp
    app-type: game
    scope-type: game
    scan-packages: com.tny.game.net.demo,com.tny.game.net.common,com.tny.game.starter
  net:
    server:
      game-server:
        bind: 127.0.0.1:16800,127.0.0.1:16801
        event-handler: test-event-handler
        channel:
          idle-timeout: 360000
        encoder:
          security-keys:
            - abcdefghijklmn
            - opqrstuvwxyz
        decoder:
          security-keys:
            - abcdefghijklmn
            - opqrstuvwxyz
    command-task-processor:
      default:
        waitStrategy: YIELDING
        threads: 4
    session:
      user:
        offline-close-delay: 1000
        offline-max-size: 1000