tny:
  app:
    name: GameServerApp
    app-type: game
    scope-type: game
  net:
    bootstrap:
      network:
        server:
          name: game-server
          bind: 127.0.0.1:16800,127.0.0.1:16801
          channel:
            encoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
            decoder:
              message-body-codec: typeProtobufMessageBodyCodec
              security-keys:
                - abcdefghijklmn
                - opqrstuvwxyz
    command:
      processor:
        disruptor:
          setting:
            enable: true
            wait-strategy: blocking
            threads: 4
    endpoint:
      session-keeper:
        name: user
        offline-close-delay: 1000
        offline-max-size: 1000