
apply plugin: 'maven-publish'

dependencies {

    annotationProcessor libs.springBootConfigurationProcessor

    api libs.springBootAutoconfigure
    api libs.aspectjrt

    api project(':tny-game-basics')
    api project(':tny-game-doc')
    api project(':tny-game-protoex')
    api project(':tny-game-data')
    api project(':tny-game-codec-jprotobuf')
    api project(':tny-game-common-scheduler')

    compileOnly project(':tny-game-data-mongodb')

}

