
apply plugin: 'maven-publish'

//    main {
//        groovy.srcDirs += ["src/main/groovy"]

dependencies {
    api project(':tny-game-net')
    api libs.xstream
    api project(':tny-game-doc-annotation')
    api project(':tny-game-common-lang')
    api project(':tny-game-rpc')
    api project(':tny-game-scanning')
    api project(':tny-game-expr-mvel')
    api libs.jacksonCore
    api libs.guava
    api libs.jacksonDatabind
    api libs.jacksonAnnotations

}

